/*
======================================================================================================================
DDL Script: Create Bronze Tables
======================================================================================================================
Script PurposeL
  This script creates tables in the 'bronze' schema, dropping existing tables in they already exist.
Run this script to re-define the DDL structure of 'bronze' Tables
======================================================================================================================
*/

